name: m
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.s
  # positioned_tap_detector: ^1.0.3
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  flutter_rating_bar: ^3.0.1+1
  google_maps_flutter: ^0.5.25+2
  google_fonts: ^0.3.10
  shared_preferences: ^0.5.6+3
  font_awesome_flutter: ^8.8.1
  cached_network_image: ^2.0.0
  shimmer: ^1.1.0
  # flutter_range_slider: ^1.4.0
  flutter_screenutil: ^1.1.0
  auto_size_text: ^2.1.0
  rive: ^0.0.1
  splashscreen: ^1.2.0
  after_layout: ^1.0.7+2
  # flutter_svg: ^0.17.4
  get: ^1.11.6
  # sqflite: ^1.3.0
  # expandable: ^4.1.3
  # path: ^1.6.4
  # open_file: ^3.0.1
  file_picker: ^1.6.2
  email_validator: ^1.0.4
  dio: ^3.0.9
  # pull_to_refresh: ^1.5.8
  carousel_slider: ^2.0.0
  progress_dialog: ^1.2.2
  geolocator: ^5.3.1
  # geocoder: ^0.2.1
  carousel_pro: ^1.0.0
  photo_view: ^0.9.2
  # edit_distance: ^0.4.1
  extended_nested_scroll_view: ^0.4.0
  connectivity: ^0.4.8+5
  data_connection_checker: ^0.3.4

  permission_handler: ^5.0.0+hotfix.5
  location_permissions: ^2.0.5
  tuple: ^1.0.3


































dev_dependencies: 
  flutter_launcher_icons: "^0.7.3"
  flutter_launcher_name: "^0.0.1"


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/logo.png"

flutter_launcher_name:
  name: "Touri"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/flare/
    - assets/images/

  fonts:
    - family: SFUIText
      fonts:
        - asset: assets/fonts/sf/SFUIText-Regular.ttf
          weight: 500
        - asset: assets/fonts/sf/SFUIText-Semibold.ttf
          weight: 700
          
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/roboto/RobotoSlab-Bold.ttf
          weight: 900

        - asset: assets/fonts/roboto/RobotoSlab-Regular.ttf
          weight: 500


    - family: OpenSans
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Regular.ttf






  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
