name: m
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.1.2
  flutter_rating_bar: ^3.0.1+1
  google_maps_flutter: ^0.5.28+1
  google_fonts: ^0.3.10
  shared_preferences: ^0.5.7+3
  font_awesome_flutter: ^8.8.1
  cached_network_image: ^2.2.0+1
  shimmer: ^1.1.1
  flutter_screenutil: ^1.1.0
  auto_size_text: ^2.1.0
  rive: ^0.0.1
  splashscreen: ^1.2.0
  after_layout: ^1.0.7+2
  webview_flutter: ^0.3.22+1
  xml: ^4.2.0
  file_picker: ^1.9.0+1
  email_validator: ^1.0.4
  dio: ^3.0.9
  carousel_slider: ^2.1.0
  progress_dialog: ^1.2.3
  geolocator: ^5.3.1
  carousel_pro: ^1.0.0
  photo_view: ^0.9.2
  extended_nested_scroll_view: ^1.0.0
  connectivity: ^0.4.8+6
  data_connection_checker: ^0.3.4
  http: ^0.12.1
  extended_image: ^0.9.0
  permission_handler: ^5.0.0+hotfix.8
  location_permissions: ^2.0.5
  tuple: ^1.0.3
  intl: ^0.16.1
  flutter_webview_plugin: ^0.3.11
  device_info: ^0.4.2+4
  uuid: ^2.0.4



dev_dependencies: 
#  flutter_launcher_icons: "^0.7.3"
  flutter_launcher_name: "^0.0.1"


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/logo.png"

flutter_launcher_name:
  name: "Touri"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/flare/
    - assets/images/

  fonts:
    - family: SFUIText
      fonts:
        - asset: assets/fonts/sf/SFUIText-Regular.ttf
          weight: 500
        - asset: assets/fonts/sf/SFUIText-Semibold.ttf
          weight: 700
          
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/roboto/RobotoSlab-Bold.ttf
          weight: 900

        - asset: assets/fonts/roboto/RobotoSlab-Regular.ttf
          weight: 500


    - family: OpenSans
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Regular.ttf






